trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

stages:
  - stage: 'Replace_Tokens'
    variables:
      - group: REPLACE_TOKENS_JSON_VARS
    displayName: 'ReplaceTokens'
    jobs:
      - job: 'Build'
        displayName: 'Replace Tokens'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: replacetokens@5
            displayName: 'Replace tokens in JSON'
            inputs:
              targetFiles: '$(System.DefaultWorkingDirectory)/azure-pipelines-yaml/replace-tokens-json-xml-azure-pipelines/appsettings.json'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true

          - bash: |
              cat appsettings.json
            displayName: Print JSON contents
            workingDirectory: '$(System.DefaultWorkingDirectory)/azure-pipelines-yaml/replace-tokens-json-xml-azure-pipelines'
