trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

variables:
  - name: System.Debug
    value: true

stages:
  - stage: 'FileTransformXML'
    displayName: 'FileTransformXML'
    jobs:
      - job: 'FileTransformXML'
        displayName: 'FileTransformXML'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - bash: |
              cat file-transform-xml-azdo-task/Web.config
            displayName: Print XML initial

          - task: FileTransform@2
            displayName: 'File transform v2 XML'
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/file-transform-xml-azdo-task'
              enableXmlTransform: true
              enableXmlVariableSubstitution: false
              xmlTransformationRules: '-transform Web.Release.config -xml Web.config'
              xmlTargetFiles: 'Web.config'

          - bash: |
              cat file-transform-xml-azdo-task/Web.config
            displayName: Print XML transformed
